"""Blame analysis engine for multi-agent execution graphs.

Pure Python (networkx only), no I/O. Public API: find_blame(); the helpers
condense, detect_loop_anomalies, select_candidates, compute_confidence and
downstream_cost are exported for tests.
"""

from .blame import find_blame
from .condense import Condensation, SuperNode, condense
from .confidence import compute_confidence
from .cost import downstream_cost
from .cutpoint import Candidate, select_candidates
from .defect import (
    REASON_INPUT_ALREADY_FLAWED,
    REASON_NO_CONTENT_CANDIDATE,
    REASON_NO_FORM_VERIFIER,
    REASON_ORCHESTRATION_LAYER,
    Defect,
    Design,
    External,
    FindingRef,
    Localized,
    Origin,
    Unlocalized,
    deserialize_defect,
    serialize_defect,
    supporting_refs,
)
from .derive import (
    DIVERGENCE_KINDS,
    QUALITY_REPORT_TYPES,
    derive_escalation,
    derive_incident,
    derive_report_type,
    reconcile,
)
from .finding import (
    PROV_CONTRACT_PROPAGATION,
    PROV_DELIVERABLE_PAYLOAD,
    PROV_INPUT_OUTPUT_DIFF,
    PROV_PER_NODE_QUALITY_DELTA,
    PROV_PER_NODE_QUALITY_JUDGE,
    PROV_RECONCILE_FACT_KEY,
    PROV_REQUIRED_SECTION_CHECK,
    PROV_TERMINAL_JUDGE_CONTENT,
    PROV_TERMINAL_JUDGE_FORM,
    PROV_VERIFIER_CHARTER_ROSTER,
    PROV_VERIFIER_JUDGE,
    PROVENANCE_LABELS,
    Finding,
    HarnessState,
    JudgePrompt,
    Provenance,
    RuleFingerprint,
    Upstream,
    UserRequest,
    deserialize_finding,
    file_type_token,
    provenance_label,
    serialize_finding,
)
from .loops import detect_loop_anomalies
from .narrative import (
    CandidacyRecord,
    NoteRecord,
    deserialize_candidacy,
    deserialize_note,
    find_notes,
    has_note,
    render_candidacy,
    render_defect,
    render_finding,
    origin_reason_phrase,
    render_note,
    render_notes,
    render_score_override_reason,
    serialize_candidacy,
    serialize_note,
)
from .roles import (
    PLANNER_PREFIXES,
    VERIFIER_PHRASES,
    VERIFIER_SUBSTRINGS,
    VERIFIER_TOKENS,
    is_planner,
    is_verifier,
)
from .types import (
    BlameConfig,
    BlameInput,
    BlameReport,
    Evidence,
    LoopAnomaly,
    LoopBaseline,
    NodeScore,
    ReportType,
    TerminalVerdict,
)

__version__ = "0.2.0"

__all__ = [
    "find_blame",
    "condense",
    "select_candidates",
    "detect_loop_anomalies",
    "compute_confidence",
    "downstream_cost",
    "Candidate",
    "Condensation",
    "SuperNode",
    "BlameConfig",
    "BlameInput",
    "BlameReport",
    "Evidence",
    "LoopAnomaly",
    "LoopBaseline",
    "NodeScore",
    "ReportType",
    "TerminalVerdict",
    # Schema-2 typed layers (verdict refactor §2)
    "Finding",
    "Provenance",
    "UserRequest",
    "HarnessState",
    "Upstream",
    "RuleFingerprint",
    "JudgePrompt",
    "serialize_finding",
    "deserialize_finding",
    "file_type_token",
    "provenance_label",
    "PROVENANCE_LABELS",
    "PROV_PER_NODE_QUALITY_JUDGE",
    "PROV_PER_NODE_QUALITY_DELTA",
    "PROV_TERMINAL_JUDGE_CONTENT",
    "PROV_TERMINAL_JUDGE_FORM",
    "PROV_VERIFIER_JUDGE",
    "PROV_VERIFIER_CHARTER_ROSTER",
    "PROV_RECONCILE_FACT_KEY",
    "PROV_DELIVERABLE_PAYLOAD",
    "PROV_INPUT_OUTPUT_DIFF",
    "PROV_REQUIRED_SECTION_CHECK",
    "PROV_CONTRACT_PROPAGATION",
    "Defect",
    "FindingRef",
    "supporting_refs",
    "DIVERGENCE_KINDS",
    "Origin",
    "Localized",
    "Unlocalized",
    "External",
    "Design",
    "REASON_ORCHESTRATION_LAYER",
    "REASON_NO_CONTENT_CANDIDATE",
    "REASON_INPUT_ALREADY_FLAWED",
    "REASON_NO_FORM_VERIFIER",
    "serialize_defect",
    "deserialize_defect",
    "derive_report_type",
    "derive_escalation",
    "derive_incident",
    "QUALITY_REPORT_TYPES",
    "reconcile",
    "render_finding",
    "render_defect",
    # Narrative layer: typed rationale records + their templates (§2.4)
    "NoteRecord",
    "CandidacyRecord",
    "serialize_note",
    "deserialize_note",
    "serialize_candidacy",
    "deserialize_candidacy",
    "render_note",
    "render_notes",
    "render_candidacy",
    "render_score_override_reason",
    "origin_reason_phrase",
    "find_notes",
    "has_note",
    # Node-role heuristics (single home; the worker imports these)
    "is_verifier",
    "is_planner",
    "VERIFIER_TOKENS",
    "VERIFIER_SUBSTRINGS",
    "VERIFIER_PHRASES",
    "PLANNER_PREFIXES",
]
